#!/bin/sh

ENABLED=yes
PROCS=stubby
ARGS="-g -C /opt/etc/stubby/stubby.yml"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
